### ISSUE TITLE
zig-cache getting created on save

### ISSUE THREAD

**Issue by iguessthislldo** [ziglang/zig.vim#13]
When writing a zig file, a `zig-cache` directory gets created in the current directory, which I would prefer not to happen. I am using neovim 0.2.2.

**Comment by iguessthislldo** [comment]
So I got around at looking at this again and figured out the auto formatter is on by default, which isn't what the README is implying. I think either `zig.vim` or `README.md` should be changed to be consistent.

**Comment by andrewrk** [comment]
I can't think of why the auto formatter would be creating a zig-cache directory. Can you double check that this happens in the latest version of zig?

**Comment by iguessthislldo** [comment]
I'm not sure what you define to be latest, but I'm using 0.4.0. I went ahead and tried `zig fmt` outside of vim with the master 2019-06-11 release and it is indeed not creating zig-cache.

**Comment by andrewrk** [comment]
I believe 0.4.0 implements zig fmt essentially by doing `zig run fmt.zig` which does a compilation of .zig file and caches it and then runs it as a child process. In master branch, the zig binary is a hybrid of c++ and zig code, and `zig fmt` is implemented directly in zig, compiled into the compiler! So this issue is one nice example of how that is an improvement.

**Comment by iguessthislldo** [comment]
Alright, but what about the auto formatter being on by default? Regardless of what `zig fmt` is doing the README implies that it won't auto format by default, which is wrong.

**Comment by andrewrk** [comment]
I agree that the readme docs should agree with the config. Am I not understanding this code correctly? It seems off by default to me:

https://github.com/ziglang/zig.vim/blob/920e808f3ff5de3ab33d99a83edb2485acee79be/autoload/zig/config.vim#L17-L19

**Comment by iguessthislldo** [comment]
Yeah, that's what I thought too, but I figured out the default is actually getting set here: https://github.com/ziglang/zig.vim/blob/920e808f3ff5de3ab33d99a83edb2485acee79be/plugin/zig.vim#L6-L10
I can change that to 0 and it fixes it.

**Comment by andrewrk** [comment]
Now that I'm forced to make a choice about it, I think I will keep it on by default and change the docs. Thanks! Done in 636fc7a21f63a884d6065afbc773b23013cea1cf
