### ISSUE TITLE
Add neovim instructions

### ISSUE THREAD

**Issue by kavika13** [ziglang/zig.vim#18]
I just started using neovim, apparently it requires special instructions for plugin install. The standard instructions for installing vim plugins didn't work for me.

I had to install [junegunn/vim-plug](https://github.com/junegunn/vim-plug) first, then I set up this plugin by adding these lines to my `~/.config/nvim/init.vim`:

```vim
call plug#begin(stdpath('data') . '/plugged')
Plug 'ziglang/zig.vim'
call plug#end()
```

Then launched nvim, `:PlugInstall`, and it installed the plugin. Restarted nvim and syntax highlighting was working for my zig files.

**Comment by andrewrk** [comment]
based on neovim.io web page:

> Drop-in Vim

>     Fully compatible with Vim's editing model and the Vimscript language. 

>  "OMG! @Neovim just works :)" —@mehowte 

sounds like a bug in neovim.

**Comment by tiehuis** [comment]
This looks to be relevant: https://stackoverflow.com/questions/48700563/how-do-i-install-plugins-in-neovim-correctly?answertab=votes#tab-top

Summarizing, it appears that neovim uses a different path for native-loading plugins. I expect this would work as expected if following this folder structure, but haven't tested.

**Comment by kavika13** [comment]
I'll test that path tiehuis linked to and get back to you.

**Comment by kavika13** [comment]
Tried it out, works without additional plugin infrastructure. Just needs a different directory.

Could opt not to add these if you want, but could be convenient for some users?

**Comment by Zooce** [comment]
I was just doing some setup to start working with Zig, and found this issue. `vim-plug` will put your plugins wherever you tell it when you do `call plug#begin(<wherever you want your plugins)`. I'm relatively new to vim, but I've noticed that most install instructions for `vim-plug` plugins don't even bother showing the call to `begin`, probably to avoid any confusion. The `vim-plug` install instructions for `zig.vim` should just be something like this:

If using **vim-plug**:
* Add `Plug 'ziglang/zig.vim'` to your config

Would anyone be opposed to me adding this to the README?
