### ISSUE TITLE
weird syntax highlighting

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig.vim#43]
I pulled to latest master branch here and seeing things that don't make sense to me.

1. builtin functions the same weight & color as `if` and `else` control flow is weird and misleading

![image](https://user-images.githubusercontent.com/106511/108927396-32de9600-760e-11eb-916b-faf4df578d52.png)

2. why are defer and catch the same different color? `catch` and `try` should be the same color.

![image](https://user-images.githubusercontent.com/106511/108927469-573a7280-760e-11eb-812c-aad0265ea49f.png)

3. `and` and `or` are the same as `const` and `var` which makes no sense. they are control flow statements, whereas `const` and `var` relate to storage.

![image](https://user-images.githubusercontent.com/106511/108927568-83ee8a00-760e-11eb-902c-5d15c40a2c97.png)

4. `try` is colored the same as `pub` and `fn` but `return` and `break` are colored different than `try`

![image](https://user-images.githubusercontent.com/106511/108927724-d2038d80-760e-11eb-8933-958f8f837845.png)

**Comment by haze** [comment]
This is a theme but as there are now more groups for different language keywords and constructs, I will update that theme later today. Please feel free to reopen if you feel there is more to be discussed about this.
