### ISSUE TITLE
error on saving file

### ISSUE THREAD

**Issue by esheldon** [ziglang/zig.vim#45]
`vim 8.0.1453`
Installed using `vim-plug`

when I save a file with `:w`, the file is saved but first I see this error

```
Error detected while processing function <SNR>32_fmt_autosave[2]..zig#fmt#Format:                                                                                                              
line   23: 
```
This hangs until I hit a key.

Briefly there is also an error printed `Unknown function: deletebufline`, but this disappears after a second or so.

**Comment by esheldon** [comment]
Thanks, works for me

**Comment by haze** [comment]
Thanks to @LemonBoy :D
