### ISSUE TITLE
`orelse` does not have syntax highlighting.

### ISSUE THREAD

**Issue by g-w1** [ziglang/zig.vim#52]
![image](https://user-images.githubusercontent.com/58830309/117887374-99bf3300-b27e-11eb-81a5-f965f0c2f1f9.png)
I think it is a builtin kword and therefore should have different color.

**Comment by haze** [comment]
`or`, `and`, and `orelse` are grouped under `zigComparatorWord`, which is linked as being highlighted as `Operator`.

Since the official zig language reference lists these are actual keywords instead of operators (as there is a separate operator table), I think this should be changed. Addressing...
