### ISSUE TITLE
Quotation marks have a different color from the rest of string literals

### ISSUE THREAD

**Issue by rsaihe** [ziglang/zig.vim#64]
For example, in a simple hello world program:

![Screenshot from 2021-09-24 10-43-14](https://user-images.githubusercontent.com/50564448/134703588-51d7dc12-6ba9-45ad-ae1a-f6cd42552da4.png)

**Comment by matu3ba** [comment]
You dont show a screenshot of the change. 

I am curious: How does this improve readability?

Is `"` not a delimiter for beginning and end of string, which could be colored different for consistency?

**Comment by rsaihe** [comment]
Every other syntax highlighting displays the quotation marks with the same color as the text they enclose. My change makes this plugin consistent with the highlighting for every other language.

**Comment by rsaihe** [comment]
Unfortunately my current operating system is having some issues taking screenshots at this time, so I cannot attach one.
