### ISSUE TITLE
request: revert #60

### ISSUE THREAD

**Issue by nektro** [ziglang/zig.vim#69]
enabling `--ast-check` causes `zig fmt` to not work in many cases during development since unused variables is now a check under AstGen.

not having the code properly formatted can making solving these errors much harder than they over wise would be

#60

**Comment by nektro** [comment]
not having the code properly formatted can making solving these errors much harder than they over wise would be

**Comment by haze** [comment]
I disagree with this sentiment: I often use the sign that if my code doesn't auto format that there is an error somewhere, so I appreciate unused variables causing that
