### ISSUE TITLE
Something about `zig fmt`

### ISSUE THREAD

**Issue by wisonye** [ziglang/zig.vim#90]
Love this plugin except for one thing I hope to be solved:

I found that each statement is always a single line after formatted:

<img width="1786" alt="1" src="https://user-images.githubusercontent.com/3477321/222868189-4f4b0f80-fb07-4f6a-ae02-266f2b04ff79.png">

Is that possible `zig fmt` can accept the following style result by whatever options? As I think that's important for using vertical split in Laptop screen size to edit 2 source files at the same time:)

<img width="972" alt="2" src="https://user-images.githubusercontent.com/3477321/222868194-ad54398c-540a-4ec0-8de1-47d6b57adc63.png">

For example, this is the formatted result after I copy&paste into `C` file, it looks much better than a long long single line:

<img width="764" alt="Screen Shot 2023-03-04 at 2 55 15 PM" src="https://user-images.githubusercontent.com/3477321/222869623-8b451093-1dbe-43b7-8de1-fd0fedd66d1f.png">

I mean at least have an optional configuration file for `zig fmt`? (enable or disable part of the format rather than encapsulate all format policies  inside and can't change?)

Sorry, I'm new to `zig`, love to learn more:)

**Comment by ratfactor** [comment]
@wisonye The answer is to use a **trailing comma** when you want each element on a separate line.

**Without** a comma after `baz`, zig fmt produces this:

```
.{ foo, bar, baz }
```

**With** a comma after `baz`, zig fmt produces this:

```
.{
    foo,
    bar,
    baz,
}
```

I personally think this is very clever and I like it, but you have to know the trick!

**Comment by wisonye** [comment]
> @wisonye The answer is to use a **trailing comma** when you want each element on a separate line.
> 
> **Without** a comma after `baz`, zig fmt produces this:
> 
> ```
> .{ foo, bar, baz }
> ```
> 
> **With** a comma after `baz`, zig fmt produces this:
> 
> ```
> .{
>     foo,
>     bar,
>     baz,
> }
> ```
> 
> I personally think this is very clever and I like it, but you have to know the trick!

Yup thanks, actually I got the answer already from the Zig discord, just forgot to close this issue, thanks anyway :)
